package com.lenovo.invoice.domain;

import java.util.Date;

public class ChangeInvoiceHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_invoice_history.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_invoice_history.zid
     *
     * @mbggenerated
     */
    private Long zid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_invoice_history.CustomerName
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_invoice_history.oTaxNo
     *
     * @mbggenerated
     */
    private String otaxno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_invoice_history.nTaxNo
     *
     * @mbggenerated
     */
    private String ntaxno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_invoice_history.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_invoice_history.id
     *
     * @return the value of change_invoice_history.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_invoice_history.id
     *
     * @param id the value for change_invoice_history.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_invoice_history.zid
     *
     * @return the value of change_invoice_history.zid
     *
     * @mbggenerated
     */
    public Long getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_invoice_history.zid
     *
     * @param zid the value for change_invoice_history.zid
     *
     * @mbggenerated
     */
    public void setZid(Long zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_invoice_history.CustomerName
     *
     * @return the value of change_invoice_history.CustomerName
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_invoice_history.CustomerName
     *
     * @param customername the value for change_invoice_history.CustomerName
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_invoice_history.oTaxNo
     *
     * @return the value of change_invoice_history.oTaxNo
     *
     * @mbggenerated
     */
    public String getOtaxno() {
        return otaxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_invoice_history.oTaxNo
     *
     * @param otaxno the value for change_invoice_history.oTaxNo
     *
     * @mbggenerated
     */
    public void setOtaxno(String otaxno) {
        this.otaxno = otaxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_invoice_history.nTaxNo
     *
     * @return the value of change_invoice_history.nTaxNo
     *
     * @mbggenerated
     */
    public String getNtaxno() {
        return ntaxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_invoice_history.nTaxNo
     *
     * @param ntaxno the value for change_invoice_history.nTaxNo
     *
     * @mbggenerated
     */
    public void setNtaxno(String ntaxno) {
        this.ntaxno = ntaxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_invoice_history.createTime
     *
     * @return the value of change_invoice_history.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_invoice_history.createTime
     *
     * @param createtime the value for change_invoice_history.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}