package com.lenovo.invoice.domain;

import java.util.Date;

public class MemberVatInvoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membervatinvoice.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membervatinvoice.InvoiceInfoId
     *
     * @mbggenerated
     */
    private Long invoiceinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membervatinvoice.LenovoID
     *
     * @mbggenerated
     */
    private String lenovoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membervatinvoice.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    private int shopid;


    private String faid;
    private String storesid;
    private String type;

    public String getFaid() {
        return faid;
    }

    public void setFaid(String faid) {
        this.faid = faid;
    }

    public String getStoresid() {
        return storesid;
    }

    public void setStoresid(String storesid) {
        this.storesid = storesid;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membervatinvoice.Id
     *
     * @return the value of membervatinvoice.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membervatinvoice.Id
     *
     * @param id the value for membervatinvoice.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membervatinvoice.InvoiceInfoId
     *
     * @return the value of membervatinvoice.InvoiceInfoId
     *
     * @mbggenerated
     */
    public Long getInvoiceinfoid() {
        return invoiceinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membervatinvoice.InvoiceInfoId
     *
     * @param invoiceinfoid the value for membervatinvoice.InvoiceInfoId
     *
     * @mbggenerated
     */
    public void setInvoiceinfoid(Long invoiceinfoid) {
        this.invoiceinfoid = invoiceinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membervatinvoice.LenovoID
     *
     * @return the value of membervatinvoice.LenovoID
     *
     * @mbggenerated
     */
    public String getLenovoid() {
        return lenovoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membervatinvoice.LenovoID
     *
     * @param lenovoid the value for membervatinvoice.LenovoID
     *
     * @mbggenerated
     */
    public void setLenovoid(String lenovoid) {
        this.lenovoid = lenovoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membervatinvoice.CreateTime
     *
     * @return the value of membervatinvoice.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membervatinvoice.CreateTime
     *
     * @param createtime the value for membervatinvoice.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public int getShopid() {
        return shopid;
    }

    public void setShopid(int shopid) {
        this.shopid = shopid;
    }
}