package com.lenovo.invoice.domain;

import java.io.Serializable;
import java.util.Date;

public class O2oVatInvoice implements Serializable {

    private Long id;


    private String customername;


    private String taxno;


    private String bankname;


    private String accountno;


    private String address;


    private String phoneno;


    private Boolean ischeck;


    private Date createtime;


    private String createby;


    private Date updatetime;


    private String updateby;


    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o2ovatinvoice.Type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o2ovatinvoice.Faid
     *
     * @mbggenerated
     */
    private String faid;

    private String storeId;
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.Id
     *
     * @param id the value for o2ovatinvoice.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.CustomerName
     *
     * @return the value of o2ovatinvoice.CustomerName
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.CustomerName
     *
     * @param customername the value for o2ovatinvoice.CustomerName
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.TaxNo
     *
     * @return the value of o2ovatinvoice.TaxNo
     *
     * @mbggenerated
     */
    public String getTaxno() {
        return taxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.TaxNo
     *
     * @param taxno the value for o2ovatinvoice.TaxNo
     *
     * @mbggenerated
     */
    public void setTaxno(String taxno) {
        this.taxno = taxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.BankName
     *
     * @return the value of o2ovatinvoice.BankName
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.BankName
     *
     * @param bankname the value for o2ovatinvoice.BankName
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.AccountNo
     *
     * @return the value of o2ovatinvoice.AccountNo
     *
     * @mbggenerated
     */
    public String getAccountno() {
        return accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.AccountNo
     *
     * @param accountno the value for o2ovatinvoice.AccountNo
     *
     * @mbggenerated
     */
    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.Address
     *
     * @return the value of o2ovatinvoice.Address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.Address
     *
     * @param address the value for o2ovatinvoice.Address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.PhoneNo
     *
     * @return the value of o2ovatinvoice.PhoneNo
     *
     * @mbggenerated
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.PhoneNo
     *
     * @param phoneno the value for o2ovatinvoice.PhoneNo
     *
     * @mbggenerated
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.isCheck
     *
     * @return the value of o2ovatinvoice.isCheck
     *
     * @mbggenerated
     */
    public Boolean getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.isCheck
     *
     * @param ischeck the value for o2ovatinvoice.isCheck
     *
     * @mbggenerated
     */
    public void setIscheck(Boolean ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.CreateTime
     *
     * @return the value of o2ovatinvoice.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.CreateTime
     *
     * @param createtime the value for o2ovatinvoice.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.CreateBy
     *
     * @return the value of o2ovatinvoice.CreateBy
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.CreateBy
     *
     * @param createby the value for o2ovatinvoice.CreateBy
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.UpdateTime
     *
     * @return the value of o2ovatinvoice.UpdateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.UpdateTime
     *
     * @param updatetime the value for o2ovatinvoice.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.UpdateBy
     *
     * @return the value of o2ovatinvoice.UpdateBy
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.UpdateBy
     *
     * @param updateby the value for o2ovatinvoice.UpdateBy
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.ShopId
     *
     * @return the value of o2ovatinvoice.ShopId
     *
     * @mbggenerated
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.ShopId
     *
     * @param shopid the value for o2ovatinvoice.ShopId
     *
     * @mbggenerated
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o2ovatinvoice.Faid
     *
     * @return the value of o2ovatinvoice.Faid
     *
     * @mbggenerated
     */
    public String getFaid() {
        return faid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o2ovatinvoice.Faid
     *
     * @param faid the value for o2ovatinvoice.Faid
     *
     * @mbggenerated
     */
    public void setFaid(String faid) {
        this.faid = faid;
    }

    public String getStoreId() {
        return storeId;
    }

    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }
}