package com.lenovo.invoice.domain;

import java.io.Serializable;
import java.util.Date;

public class VatInvoice  implements Serializable {

    private Long id;
    private String customername;
    private String taxno;
    private String bankname;
    private String accountno;
    private String address;
    private String phoneno;
    private String btcpso;
    private Integer ischeck; //审核状态 0：未审核 1：客服审核通过 2：BTCP审核通过 3：审核驳回
    private Boolean isthrowing;
    private Date createtime;
    private String createby;
    private Date updatetime;
    private String updateby;
    private Integer isshared;
    private Integer isNeedMerge;
    private int shopid;
    private String shardedby;
    private Date shardedtime;
    private String faid;
    private String storesid;
    private String type;
    private Integer isvalid;

    private Integer taxNoType; //识别码类型，1是15位，2是18位，3是无
    private Integer custType; //开票方式，1公司，0个人
    private Integer invoiceType; //发票类型，1:电子票2:增票3:普票
    private String checkBy; //审核人
    private Date checkTime; //审核时间
    private String remark; //备注
    private Integer isDelete; //是否删除

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public Integer getTaxNoType() {
        return taxNoType;
    }

    public void setTaxNoType(Integer taxNoType) {
        this.taxNoType = taxNoType;
    }

    public Integer getCustType() {
        return custType;
    }

    public void setCustType(Integer custType) {
        this.custType = custType;
    }

    public Integer getInvoiceType() {
        return invoiceType;
    }

    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    public String getCheckBy() {
        return checkBy;
    }

    public void setCheckBy(String checkBy) {
        this.checkBy = checkBy;
    }

    public Date getCheckTime() {
        return checkTime;
    }

    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getFaid() {
        return faid;
    }

    public void setFaid(String faid) {
        this.faid = faid;
    }

    public String getStoresid() {
        return storesid;
    }

    public void setStoresid(String storesid) {
        this.storesid = storesid;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public VatInvoice() {
    }

    public VatInvoice(String customername, String taxno, String bankname, String accountno, String address, String phoneno, String type, String faid, String storesid) {
        this.customername = customername;
        this.taxno = taxno;
        this.bankname = bankname;
        this.accountno = accountno;
        this.address = address;
        this.phoneno = phoneno;
        this.type = type;
        this.faid = faid;
        this.storesid = storesid;


    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.Id
     *
     * @return the value of vatinvoice.Id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.Id
     *
     * @param id the value for vatinvoice.Id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.CustomerName
     *
     * @return the value of vatinvoice.CustomerName
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.CustomerName
     *
     * @param customername the value for vatinvoice.CustomerName
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.TaxNo
     *
     * @return the value of vatinvoice.TaxNo
     * @mbggenerated
     */
    public String getTaxno() {
        return taxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.TaxNo
     *
     * @param taxno the value for vatinvoice.TaxNo
     * @mbggenerated
     */
    public void setTaxno(String taxno) {
        this.taxno = taxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.BankName
     *
     * @return the value of vatinvoice.BankName
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.BankName
     *
     * @param bankname the value for vatinvoice.BankName
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.AccountNo
     *
     * @return the value of vatinvoice.AccountNo
     * @mbggenerated
     */
    public String getAccountno() {
        return accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.AccountNo
     *
     * @param accountno the value for vatinvoice.AccountNo
     * @mbggenerated
     */
    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.Address
     *
     * @return the value of vatinvoice.Address
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.Address
     *
     * @param address the value for vatinvoice.Address
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.PhoneNo
     *
     * @return the value of vatinvoice.PhoneNo
     * @mbggenerated
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.PhoneNo
     *
     * @param phoneno the value for vatinvoice.PhoneNo
     * @mbggenerated
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.BTCPSO
     *
     * @return the value of vatinvoice.BTCPSO
     * @mbggenerated
     */
    public String getBtcpso() {
        return btcpso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.BTCPSO
     *
     * @param btcpso the value for vatinvoice.BTCPSO
     * @mbggenerated
     */
    public void setBtcpso(String btcpso) {
        this.btcpso = btcpso;
    }

    public Integer getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.IsThrowing
     *
     * @return the value of vatinvoice.IsThrowing
     * @mbggenerated
     */
    public Boolean getIsthrowing() {
        return isthrowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.IsThrowing
     *
     * @param isthrowing the value for vatinvoice.IsThrowing
     * @mbggenerated
     */
    public void setIsthrowing(Boolean isthrowing) {
        this.isthrowing = isthrowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.CreateTime
     *
     * @return the value of vatinvoice.CreateTime
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.CreateTime
     *
     * @param createtime the value for vatinvoice.CreateTime
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.CreateBy
     *
     * @return the value of vatinvoice.CreateBy
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.CreateBy
     *
     * @param createby the value for vatinvoice.CreateBy
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.UpdateTime
     *
     * @return the value of vatinvoice.UpdateTime
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.UpdateTime
     *
     * @param updatetime the value for vatinvoice.UpdateTime
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.UpdateBy
     *
     * @return the value of vatinvoice.UpdateBy
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.UpdateBy
     *
     * @param updateby the value for vatinvoice.UpdateBy
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.IsShared
     *
     * @return the value of vatinvoice.IsShared
     * @mbggenerated
     */
    public Integer getIsshared() {
        return isshared;
    }

    public void setIscheck(Integer ischeck) {
        this.ischeck = ischeck;
    }

    public void setIsshared(Integer isshared) {
        this.isshared = isshared;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.ShardedBy
     *
     * @return the value of vatinvoice.ShardedBy
     * @mbggenerated
     */
    public String getShardedby() {
        return shardedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.ShardedBy
     *
     * @param shardedby the value for vatinvoice.ShardedBy
     * @mbggenerated
     */
    public void setShardedby(String shardedby) {
        this.shardedby = shardedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vatinvoice.ShardedTime
     *
     * @return the value of vatinvoice.ShardedTime
     * @mbggenerated
     */
    public Date getShardedtime() {
        return shardedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vatinvoice.ShardedTime
     *
     * @param shardedtime the value for vatinvoice.ShardedTime
     * @mbggenerated
     */
    public void setShardedtime(Date shardedtime) {
        this.shardedtime = shardedtime;
    }

    public Integer getIsNeedMerge() {
        return isNeedMerge;
    }

    public void setIsNeedMerge(Integer isNeedMerge) {
        this.isNeedMerge = isNeedMerge;
    }

    public int getShopid() {
        return shopid;
    }

    public void setShopid(int shopid) {
        this.shopid = shopid;
    }

    public Integer getIsvalid() {
        return isvalid;
    }

    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }
}