package com.lenovo.invoice.dao;

import com.lenovo.invoice.domain.O2oVatInvoice;
import com.lenovo.invoice.domain.O2oVatInvoiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface O2OVatInvoiceMapper {

    List<O2oVatInvoice> queryO2oVatInvoiceInfo(@Param("ids") String ids);
    List<O2oVatInvoice> getO2OVatInvoiceBySelected(O2oVatInvoice invoice);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    int countByExample(O2oVatInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    int deleteByExample(O2oVatInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    int insertO2OVatInvoiceInfo(O2oVatInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    int insertSelective(O2oVatInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    List<O2oVatInvoice> selectByExample(O2oVatInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    O2oVatInvoice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") O2oVatInvoice record, @Param("example") O2oVatInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") O2oVatInvoice record, @Param("example") O2oVatInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(O2oVatInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o2ovatinvoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(O2oVatInvoice record);
}