package com.lenovo.invoice.dao;

import com.lenovo.invoice.domain.OrderInvoice;
import com.lenovo.invoice.domain.OrderInvoiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderInvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int countByExample(OrderInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int deleteByExample(OrderInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int insert(OrderInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int insertSelective(OrderInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    List<OrderInvoice> selectByExample(OrderInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    OrderInvoice selectByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderInvoice record, @Param("example") OrderInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderInvoice record, @Param("example") OrderInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderInvoice record);
}