package com.lenovo.invoice.dao;

import com.lenovo.invoice.domain.OrderInvoice;

public interface OrderInvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int insertOrderInvoice(OrderInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int insertSelective(OrderInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    OrderInvoice selectByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinvoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderInvoice record);
}