package com.lenovo.invoice.dao;

import com.lenovo.invoice.domain.VathrowBtcp;

public interface VathrowBtcpMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vathrowbtcp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vathrowbtcp
     *
     * @mbggenerated
     */
    int insert(VathrowBtcp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vathrowbtcp
     *
     * @mbggenerated
     */
    int insertSelective(VathrowBtcp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vathrowbtcp
     *
     * @mbggenerated
     */
    VathrowBtcp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vathrowbtcp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VathrowBtcp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vathrowbtcp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VathrowBtcp record);
}